######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 13 12:15:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
